Update facts to break down to individual properties
networktocode/pyntc pull request #173
Opened 2020-11-28 19:46 UTC by mundruid

- Broke down facts to individual properties in base device and all devices that had implemented facts
- Modified unit tests for properties
- Addresses issue #99

2020-12-01 19:48 UTC, jmcgill298 requested changes
Good work @mundruid there are a few comments I have provided, but there are 3 items that should be looked at all around that were not commented each time:

1. Lets keep `vendor` as a class attribute as this should be constant
2. The `_get_*` methods were created to simplify the large `facts` property. Since this is being broken into smaller individual pieces, the logic in those internal methods can be moved to the respective property
3. The `if` conditional for checking if the property has already been discovered should be at the top of each property. This will speed things up and prevent wasting time/cpu resources trying to run commands on the device


Thanks

2020-12-01 19:48 UTC, jmcgill298 commented on pyntc/devices/eos_device.py
> +            self._hostname = convert_dict_by_key(sh_hostname_output, {}, fill_in=True, whitelist=["hostname"])[
I believe we can just do `self._hostname = show_hostname_output["hostname"]`

2020-12-01 19:48 UTC, jmcgill298 commented on pyntc/devices/eos_device.py
> +            self._fqdn = convert_dict_by_key(sh_hostname_output, {}, fill_in=True, whitelist=["fqdn"])["fqdn"]
I believe we can just do `self._fqdn= show_hostname_output["fqdn"]`

2020-12-01 19:48 UTC, jmcgill298 commented on pyntc/devices/eos_device.py
> +            self._interfaces = self._get_interface_list()
lets move this logic from the internal method to hear and whatever needs that can just reference the property

2020-12-01 19:48 UTC, jmcgill298 commented on pyntc/devices/eos_device.py
> +            self._vlans = self._get_vlan_list()
lets move this logic from the internal method to hear and whatever needs that can just reference the property

2020-12-01 19:48 UTC, jmcgill298 commented on pyntc/devices/ios_device.py
> +        if self._uptime is None:
This should be moved to the first line of the property

2020-12-01 19:48 UTC, jmcgill298 commented on pyntc/devices/ios_device.py
> +        if self._uptime_string is None:
This should be moved to the first line of the property

2020-12-01 19:48 UTC, jmcgill298 commented on pyntc/devices/ios_device.py
> +    def cisco_ios_ssh(self):
lets just change this to a `config_register` property and lose the dictionary

2020-12-02 15:06 UTC, mundruid commented
> Good work @mundruid there are a few comments I have provided, but there are 3 items that should be looked at all around that were not commented each time:
> 
> 1. Lets keep `vendor` as a class attribute as this should be constant
> 2. The `_get_*` methods were created to simplify the large `facts` property. Since this is being broken into smaller individual pieces, the logic in those internal methods can be moved to the respective property
> 3. The `if` conditional for checking if the property has already been discovered should be at the top of each property. This will speed things up and prevent wasting time/cpu resources trying to run commands on the device
> 
> Thanks

@jmcgill298, 

Thanks for the review. These are good points, especially the second one on improving speed. I will address these  by EOBD today so that we can merge since there are several other PRs in the stack.

Thanks!

2020-12-04 21:48 UTC, mundruid commented on pyntc/devices/base_device.py
> +        self._vendor = None
Addressed in next commit.

2020-12-04 22:32 UTC, mundruid commented on pyntc/devices/eos_device.py
> +    def _get_uptime(self):
Addressed in next commit.

2020-12-05 11:59 UTC, mundruid commented
@jmcgill298 I have addressed all your comments. Please let me know if I am missing anything.

2020-12-05 15:03 UTC, jmcgill298 approved these changes

2020-12-05 15:04 UTC, merged

2020-12-05 15:05 UTC, jmcgill298 commented
Thanks @mundruid