Remove confirm keyword requirement from device reboot
networktocode/pyntc pull request #191
Opened 2021-01-06 19:20 UTC by mundruid

- Remove confirm keyword from all devices reboot
- Addresses issue #94

2021-01-10 17:35 UTC, jmcgill298 requested changes
Thanks @mundruid, one comment, can you add `**kwargs` to the reboot method and send a warning that passing `confirm` is deprecated if confirm is in kwargs?

```
def reboot(..., **kwargs):
    if confirm in reboot:
        warnings.warn("passing 'confirm' to reboot method is deprecated..", DeprecationWarning)
```

2021-01-23 19:51 UTC, mundruid commented
> Thanks @mundruid, one comment, can you add `**kwargs` to the reboot method and send a warning that passing `confirm` is deprecated if confirm is in kwargs?
> 
> ```
> def reboot(..., **kwargs):
>     if confirm in reboot:
>         warnings.warn("passing 'confirm' to reboot method is deprecated..", DeprecationWarning)
> ```

Thanks for the review @jmcgill298 . It's a good point for backward compatibility and I added this. 

I added tests in the unit tests to check if the warning is triggered. We can remove them if we consider them unnecessary. I only added unit tests for two types unit with fixtures and without, i.e., asa and aireos, since the deprecation code is the same for all.

2021-01-24 02:58 UTC, jmcgill298 commented on pyntc/devices/asa_device.py
> +            RebootSignal: When the device is still unreachable after the timeout period.
```suggestion
            RebootTimeoutError: When the device is still unreachable after the timeout period.
```

2021-01-24 02:59 UTC, jmcgill298 approved these changes

2021-01-24 03:01 UTC, jmcgill298 commented
Thanks @mundruid I rebased b/c I saw commits that shouldn't be there, then I realized that the issue was the PR was into the main branch instead of develop. I fixed that, and I updated an incorrect docstring (it wasn't something you changed, just noticed it in the review). I will merge once tests pass

2021-01-24 03:03 UTC, merged