Merge config() and config_list() for Juniper.
networktocode/pyntc pull request #196
Opened 2021-01-19 18:12 UTC by jeffkala

Deprecation warning for config_list() and repoint it to config() which now turns str into list, and runs commands through for loop to load them into config.

2021-01-19 19:26 UTC, jmcgill298 requested changes
Thanks again for the PR @jeffkala There is one comment on updates, and would also include the same updates to test cases as #195

2021-01-19 19:26 UTC, jmcgill298 commented on pyntc/devices/jnpr_device.py
>              raise CommandListError(commands, command, e.message)
This should check to see if `commands` was passed as a list or a string, and then raise either `CommandError` or `CommandListError` as appropriate.

2021-01-19 19:28 UTC, jeffkala commented
@jmcgill298, thanks for the review. Will implement these soon.

2021-01-22 23:03 UTC, jmcgill298 requested changes

2021-01-23 00:27 UTC, jmcgill298 approved these changes

2021-01-23 00:28 UTC, jmcgill298 commented
Thanks @jeffkala I made one change to how the config_as_list test case was validating the calls.

2021-01-23 00:28 UTC, merged