Added docstrings to eos_device.py
networktocode/pyntc pull request #206
Opened 2021-02-23 19:00 UTC by qduk

2021-03-03 11:58 UTC, mundruid requested changes
I noticed that you are using the `Returns` statement in properties that do not explicitly return. This is not a big error, but it would be better not to have the `Returns` statement when a function does not return something.

2021-03-03 11:58 UTC, mundruid commented on pyntc/devices/eos_device.py
>      def uptime(self):
This property assigns only and does not explicitly return. I think it would be better to omit the `Returns` statement in the docstring.

2021-03-03 11:58 UTC, mundruid commented on pyntc/devices/eos_device.py
> +        Returns:
This property assigns only and does not explicitly return. I think it would be better to omit the `Returns` statement in the docstring.

2021-03-03 11:58 UTC, mundruid commented on pyntc/devices/eos_device.py
> +        Returns:
Same here: This property assigns only and does not explicitly return. I think it would be better to omit the `Returns` statement in the docstring.

2021-03-03 11:58 UTC, mundruid commented on pyntc/devices/eos_device.py
> +        Returns:
This applies to all the following properties that do not explicitly return.

2021-03-03 11:58 UTC, mundruid commented on pyntc/devices/eos_device.py
> +            [type]: [description]
Missed that one: `bool: True if remote file exists.`

2021-03-29 18:17 UTC, jmcgill298 requested changes

2021-03-29 18:17 UTC, jmcgill298 commented on pyntc/devices/eos_device.py
> +        """Create backup file of running configurtation.
```suggestion
        """
        Create backup file of running configuration.
```

2021-03-29 18:17 UTC, jmcgill298 commented on pyntc/devices/eos_device.py
> +        """Create a string of the uptime of the device.
```suggestion
        """
        Get uptime of the device in the format of dd::hh::mm.
```

2021-03-29 18:17 UTC, jmcgill298 commented on pyntc/devices/eos_device.py
> +        """Get uptime from device.
```suggestion
        """
        Get uptime of the device in seconds.
```

2021-03-29 18:18 UTC, jmcgill298 approved these changes

2021-03-29 18:50 UTC, merged