Added docstrings to f5_device.py
networktocode/pyntc pull request #207
Opened 2021-02-26 07:11 UTC by qduk

2021-03-03 14:27 UTC, mundruid approved these changes
Looks good!

2021-03-29 18:23 UTC, jmcgill298 requested changes

2021-03-29 18:23 UTC, jmcgill298 commented on pyntc/devices/f5_device.py
> +            str: Name of active volume
```suggestion
            str: Name of active volume.
```

2021-03-29 18:23 UTC, jmcgill298 commented on pyntc/devices/f5_device.py
> +        """Get uptime of device in string format ``days:hours:mins:seconds``.
```suggestion
        """
        Get uptime of device in format dd:hh:mm:ss.
```

2021-03-29 18:24 UTC, jmcgill298 approved these changes

2021-03-29 19:10 UTC, merged