Add logging for all devices
networktocode/pyntc pull request #217
Opened 2021-04-09 16:11 UTC by mundruid

- Add log utility to print error messages when exceptions occur and other information messages
- Log files are created
- Addresses issue https://github.com/networktocode/pyntc/issues/110

2021-04-09 22:48 UTC, jvanderaa commented
@mundruid  This may need to get changed in the PR to using develop instead of main to help with the diffs

2021-04-10 16:41 UTC, mundruid commented
> @mundruid This may need to get changed in the PR to using develop instead of main to help with the diffs

Thanks, @jvanderaa . I keep forgetting that the default PR in this repo is main and not develop. Changed.

2021-04-12 00:46 UTC, itdependsnetworks commented
I am not sure if there is something unique about this logging (I see you are importing from pyntc.log as an example), but generally you are meant to use `%s` style formatting and not `f-string` formatting for logging.

2021-04-12 13:19 UTC, mundruid commented
> I am not sure if there is something unique about this logging (I see you are importing from pyntc.log as an example), but generally you are meant to use `%s` style formatting and not `f-string` formatting for logging.

@itdependsnetworks I am happy to make the change. I was wondering why we would prefer `%` instead of `f-string`?

2021-04-13 03:20 UTC, itdependsnetworks commented
It has to do with the lack of lazy loading in f-strings. This does a better job of explaining https://medium.com/swlh/why-it-matters-how-you-log-in-python-1a1085851205

2021-08-18 01:43 UTC, mundruid commented
> It has to do with the lack of lazy loading in f-strings. This does a better job of explaining https://medium.com/swlh/why-it-matters-how-you-log-in-python-1a1085851205

@itdependsnetworks I have addressed the comment and replaced all the f-strings. Sorry it took so long. Let me know what you think.

2021-10-04 05:31 UTC, jmcgill298 requested changes
@mundruid I started with these, so far I have only made it through the aireos driver

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +            log.error("Host %s: Netmiko Driver's {err.args[0]}", self.host, err.args[0])
```suggestion
            log.error("Host %s: Netmiko Driver's %s", self.host, err.args[0])
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +                    "Host %s: Commands {entered_commands} returned the error {err.cli_error_msg}",
```suggestion
                    "Host %s: Commands %s returned the error %s",
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +                log.error("Host %s: Commands {entered_commands} returned the error %s", self.host, entered_commands)
```suggestion
                log.error("Host %s: Commands %s returned the error %s", self.host, entered_commands, err.cli_error_msg)
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +            "Host %s: List of config commands %s received responses {command_response}.",
```suggestion
            "Host %s: List of config commands %s received responses %s.",
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +        log.warning("config_list() is deprecated; use config.", DeprecationWarning)
```suggestion
        log.warning("config_list() is deprecated; use config.")
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +        log.debug("Host %s: Connection status {self._connected}.", self.host, self._connected)
```suggestion
        log.debug("Host %s: Connection status %s.", self.host, self._connected)
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +        log.debug("Host %s: Device connected is %s.", self.host, value)
```suggestion
        log.debug("Host %s: Device connection status is %s.", self.host, value)
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +                    "Host %s: WLANS not disabled, with desired WLANs {desired_wlans} and post disabled WLANs {post_disabled_wlans}",
```suggestion
                    "Host %s: Unable to disable WLANS, with desired WLANs %s and post disabled WLANs %s",
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +        log.info("Host %s: All WLANs with IDs {disabled_wlans} were disabled.", self.host, disabled_wlans)
```suggestion
        log.info("Host %s: All WLANs with IDs %s were disabled.", self.host, disabled_wlans)
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +        log.info("Host %s: Disabled WLAN IDs: {disabled_wlans}", self.host, disabled_wlans)
```suggestion
        log.info("Host %s: Disabled WLAN IDs: %s", self.host, disabled_wlans)
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +                    f"with desired WLANs {desired_wlans} and post enabled WLANs {post_enabled_wlans}",
```suggestion
                    "with desired WLANs %s and post enabled WLANs %s",
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +                    "Host %s: WLANS not enabled,\n"
```suggestion
                    "Host %s: Unable to enable WLANs,\n"
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +        log.info("Host %s: List of enabled WLAN IDs: {enabled_wlans}", self.host, enabled_wlans)
```suggestion
        log.info("Host %s: List of enabled WLAN IDs: %s", self.host, enabled_wlans)
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +                "Host %s: File transfer error {FileTransferError.default_message}\n\n{error.message}",
```suggestion
                "Host %s: File transfer error %s\n\n%s",
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +                "Host %s: File transfer error {FileTransferError.default_message}\n\n{error.message}",
```suggestion
                "Host %s: File transfer error %s\n\n%s",
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +            log.error("Host %s: Did not find expected success message in response, found:\n%s", self.host, response)
```suggestion
            log.error("Host %s: Did not find expected success message in file transfer response, found:\n%s", self.host, response)
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +            log.info("Host %s: OS image %s installed successfully.", self.host, image_name)
```suggestion
            log.info("Host %s: OS image %s installed.", self.host, image_name)
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +        log.debug("Host %s: Redundancy mode: {ha_mode.group(1).lower()}", self.host, ha_mode.group(1).lower())
```suggestion
        log.debug("Host %s: Redundancy mode: %s", self.host, ha_mode.group(1).lower())
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +            log.error("Host %s: Netmiko Driver's {err.args[0]}", self.host, err.args[0])
```suggestion
            log.error("Host %s: Netmiko Driver's %s", self.host, err.args[0])
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +                    "Host %s: Command error for commands {entered_commands} with message {err.cli_error_msg}.",
```suggestion
                    "Host %s: Command error for commands %s with message %s.",
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +                    "Host %s: Command error for commands {entered_commands} with message %s.",
```suggestion
                    "Host %s: Command error for commands %s with message %s.",
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +            "Host %s: Successfully executed command 'show' with responses {command_responses}.",
```suggestion
            "Host %s: Successfully executed show commands with responses %s.",
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +            raise FileTransferError
```suggestion
            raise FileTransferError(f"Unable to set all APs to use {image}")
```

2021-10-04 05:31 UTC, jmcgill298 commented on pyntc/devices/aireos_device.py
> +        log.debug("Host %s: Device has been up for %s seconds", self.host, seconds)
```suggestion
        log.debug("Host %s: Device has been up for %d seconds", self.host, seconds)
```

2021-10-04 13:21 UTC, mundruid commented
> @mundruid I started with these, so far I have only made it through the aireos driver

@jmcgill298 Thanks for the review!

2022-10-18 17:22 UTC, jeffkala commented
@jmcgill298 @mundruid I know its a longshot being this PR is so old, but was this ready to go? Worth revisiting to get it over the finish line or just close?

2022-10-18 20:24 UTC, mundruid commented
@jeffkala On my part, this was ready after addressing Ken's comment about the not using `f-strings` in all the logs. I have added the tests and all the logging. However, It is a long one to review and I think that is why we have not merged it yet.

2022-10-18 20:41 UTC, jmcgill298 commented
@jeffkala I put several comments above where things do not look quite right. I did not get through all of the updates, but I suspect similar comments to be repeated

2022-10-18 20:43 UTC, jeffkala commented
@mundruid @jmcgill298 thanks, will try and work on getting the rest updated and get this PR over the finish line.

2022-12-22 23:39 UTC, jeffkala commented
taking it over the finish line in this pr #271

2022-12-22 23:39 UTC, closed without merging